-- AquaSystem Database Initialization Script
-- This script runs when PostgreSQL container starts for the first time

-- Create extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Create enum types
CREATE TYPE user_role AS ENUM ('ADMIN', 'MANAGER', 'OPERATOR', 'VIEWER');
CREATE TYPE product_category AS ENUM ('WATER_BOTTLES', 'WATER_JUGS', 'FILTERS', 'ACCESSORIES', 'DISPENSERS', 'CHEMICALS');
CREATE TYPE unit_of_measure AS ENUM ('UNIT', 'LITER', 'MILLILITER', 'BOX', 'PACK');
CREATE TYPE movement_type AS ENUM ('IN', 'OUT', 'TRANSFER_IN', 'TRANSFER_OUT', 'ADJUSTMENT', 'RETURN', 'LOSS');
CREATE TYPE sale_status AS ENUM ('PENDING', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED');
CREATE TYPE invoice_status AS ENUM ('DRAFT', 'SENT', 'PAID', 'PARTIAL', 'OVERDUE', 'CANCELLED', 'REFUNDED');
CREATE TYPE return_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'PROCESSED', 'REFUNDED');
CREATE TYPE return_condition AS ENUM ('GOOD', 'DAMAGED', 'EXPIRED', 'WRONG_PRODUCT');
CREATE TYPE payment_method AS ENUM ('CASH', 'CARD', 'TRANSFER', 'CHECK', 'DIGITAL_WALLET', 'OTHER');
CREATE TYPE payment_status AS ENUM ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED');
CREATE TYPE setting_type AS ENUM ('STRING', 'NUMBER', 'BOOLEAN', 'JSON', 'COLOR');

-- Grant permissions
GRANT ALL PRIVILEGES ON DATABASE aquasystem TO aqua;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO aqua;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO aqua;

-- Set default privileges for future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO aqua;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO aqua;