import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: [
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#0058bc',
          container: '#0070eb',
          dark: '#adc6ff',
          onPrimary: '#ffffff',
          onPrimaryContainer: '#fefcff',
        },
        secondary: {
          DEFAULT: '#405f91',
          container: '#a6c5fe',
          onSecondary: '#ffffff',
          onSecondaryContainer: '#315182',
        },
        tertiary: {
          DEFAULT: '#4c5f66',
          container: '#65777f',
          onTertiary: '#ffffff',
          onTertiaryContainer: '#fafdff',
        },
        surface: {
          DEFAULT: '#f7f9fb',
          container: '#eceef0',
          containerHigh: '#e6e8ea',
          containerHighest: '#e0e3e5',
          containerLow: '#f2f4f6',
          containerLowest: '#ffffff',
          dim: '#d8dadc',
          bright: '#f7f9fb',
          tint: '#005bc1',
          variant: '#e0e3e5',
          onSurface: '#191c1e',
          onSurfaceVariant: '#414755',
        },
        background: '#f7f9fb',
        onBackground: '#191c1e',
        outline: '#717786',
        outlineVariant: '#c1c6d7',
        inverseSurface: '#2d3133',
        inverseOnSurface: '#eff1f3',
        inversePrimary: '#adc6ff',
        error: {
          DEFAULT: '#ba1a1a',
          onError: '#ffffff',
          container: '#ffdad6',
          onErrorContainer: '#93000a',
        },
        success: {
          DEFAULT: '#00684a',
          onSuccess: '#ffffff',
          container: '#a7f5d5',
          onSuccessContainer: '#002112',
        },
        warning: {
          DEFAULT: '#8c5a00',
          onWarning: '#ffffff',
          container: '#ffdc80',
          onWarningContainer: '#2d1a00',
        },
      },
      darkMode: {
        primary: {
          DEFAULT: '#adc6ff',
          container: '#004493',
          dark: '#0058bc',
          onPrimary: '#001a41',
          onPrimaryContainer: '#d8e2ff',
        },
        secondary: {
          DEFAULT: '#a9c7ff',
          container: '#315182',
          onSecondary: '#001b3d',
          onSecondaryContainer: '#d6e3ff',
        },
        tertiary: {
          DEFAULT: '#b6cad2',
          container: '#4c5f66',
          onTertiary: '#0b1e24',
          onTertiaryContainer: '#d2e6ef',
        },
        surface: {
          DEFAULT: '#2d3133',
          container: '#3d4143',
          containerHigh: '#484c4f',
          containerHighest: '#52575b',
          containerLow: '#373b3e',
          containerLowest: '#1e2022',
          dim: '#191c1e',
          bright: '#373b3e',
          tint: '#adc6ff',
          variant: '#414755',
          onSurface: '#eff1f3',
          onSurfaceVariant: '#c1c6d7',
        },
        background: '#191c1e',
        onBackground: '#eff1f3',
        outline: '#8a91a0',
        outlineVariant: '#414755',
        inverseSurface: '#f7f9fb',
        inverseOnSurface: '#191c1e',
        inversePrimary: '#0058bc',
        error: {
          DEFAULT: '#f2b8b5',
          onError: '#601410',
          container: '#93000a',
          onErrorContainer: '#ffdad6',
        },
        success: {
          DEFAULT: '#6ad9a0',
          onSuccess: '#002112',
          container: '#004d2e',
          onSuccessContainer: '#a7f5d5',
        },
        warning: {
          DEFAULT: '#ffcc66',
          onWarning: '#2d1a00',
          container: '#4d3600',
          onWarningContainer: '#ffdc80',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'Consolas', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600', letterSpacing: '-0.01em' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500', letterSpacing: '0.01em' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
      },
      fontWeight: {
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
      lineHeight: {
        tight: '1.25',
        normal: '1.5',
        relaxed: '1.75',
      },
      letterSpacing: {
        tight: '-0.02em',
        normal: '0',
        wide: '0.01em',
      },
      spacing: {
        base: '8px',
        0: '0',
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
        20: '80px',
        24: '96px',
        gutter: '24px',
        section: '48px',
        containerPadding: {
          mobile: '16px',
          desktop: '32px',
        },
      },
      borderRadius: {
        none: '0',
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '2rem',
        full: '9999px',
      },
      boxShadow: {
        none: 'none',
        level1: '0 2px 4px rgba(15, 23, 42, 0.05)',
        level2: '0 8px 16px rgba(15, 23, 42, 0.08)',
        level3: '0 16px 32px rgba(15, 23, 42, 0.12)',
        glow: '0 0 12px rgba(0, 88, 188, 0.3)',
        glowStrong: '0 0 24px rgba(0, 88, 188, 0.5)',
        inner: 'inset 0 2px 4px rgba(15, 23, 42, 0.05)',
        focus: '0 0 0 2px #0058bc',
        focusDark: '0 0 0 2px #adc6ff',
      },
      screens: {
        mobile: '320px',
        tablet: '768px',
        desktop: '1024px',
        wide: '1280px',
        ultra: '1536px',
      },
      container: {
        center: true,
        padding: {
          DEFAULT: '16px',
          desktop: '32px',
        },
      },
      transitionDuration: {
        fast: '150ms',
        normal: '200ms',
        slow: '300ms',
      },
      transitionTimingFunction: {
        'ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'ease-out': 'cubic-bezier(0, 0, 0.2, 1)',
        'ease-in': 'cubic-bezier(0.4, 0, 1, 1)',
      },
      animation: {
        'fade-in': 'fadeIn 200ms ease-out',
        'fade-out': 'fadeOut 200ms ease-in',
        'slide-up': 'slideUp 300ms ease-out',
        'slide-down': 'slideDown 300ms ease-out',
        'scale-in': 'scaleIn 200ms ease-out',
        'spin-slow': 'spin 3s linear infinite',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
} satisfies Config;